server:
  port: 8080

spring:
  application:
    name: uml-crud-generator
  
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.basiccode: DEBUG
    org.springframework.web: INFO