package com.basiccode.generator.generator.spring;

import com.basiccode.generator.generator.IMigrationGenerator;
import com.basiccode.generator.model.EnhancedClass;
import java.util.List;

/**
 * Générateur de migrations Spring Boot (Flyway)
 */
public class SpringBootMigrationGenerator implements IMigrationGenerator {
    
    @Override
    public String generateMigration(List<EnhancedClass> enhancedClasses, String packageName) {
        StringBuilder sql = new StringBuilder();
        
        sql.append("-- Migration for multiple entities\n");
        sql.append("-- Generated by UML Code Generator\n\n");
        
        for (EnhancedClass enhancedClass : enhancedClasses) {
            String className = enhancedClass.getOriginalClass().getName();
            String tableName = toSnakeCase(className);
            
            // Create table
            sql.append("CREATE TABLE ").append(tableName).append(" (\n");
            
            // ID column
            sql.append("    id BIGINT AUTO_INCREMENT PRIMARY KEY,\n");
            
            // Attributes
            if (enhancedClass.getOriginalClass().getAttributes() != null) {
                enhancedClass.getOriginalClass().getAttributes().forEach(attr -> {
                    if (!"id".equals(attr.getName())) {
                        String columnName = toSnakeCase(attr.getName());
                        String sqlType = mapToSqlType(attr.getType());
                        sql.append("    ").append(columnName).append(" ").append(sqlType).append(",\n");
                    }
                });
            }
            
            // Timestamps
            sql.append("    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,\n");
            sql.append("    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP\n");
            
            sql.append(");\n\n");
        }
        
        return sql.toString();
    }
    
    private String mapToSqlType(String javaType) {
        switch (javaType.toLowerCase()) {
            case "string":
                return "VARCHAR(255)";
            case "int":
            case "integer":
                return "INT";
            case "long":
                return "BIGINT";
            case "float":
                return "FLOAT";
            case "double":
                return "DOUBLE";
            case "boolean":
                return "BOOLEAN";
            case "date":
                return "DATE";
            case "datetime":
                return "TIMESTAMP";
            case "uuid":
                return "VARCHAR(36)";
            default:
                return "VARCHAR(255)";
        }
    }
    
    private String toSnakeCase(String camelCase) {
        return camelCase.replaceAll("([a-z])([A-Z])", "$1_$2").toLowerCase();
    }
    
    @Override
    public String getFileExtension() {
        return ".sql";
    }
}