// Generated by Enhanced UML-to-Code Generator
package com.preslog.entity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.validation.Valid;
import java.time.Instant;
import java.util.UUID;

@Entity
@Table(
        name = "utilisateur"
)
@Valid
public class Utilisateur {
    @Id
    @GeneratedValue
    @Column(
            name = "id",
            updatable = false
    )
    private UUID id;

    @Column(
            name = "created_at",
            nullable = false,
            updatable = false
    )
    private Instant createdAt;

    @Column(
            name = "updated_at"
    )
    private Instant updatedAt;

    public Utilisateur() {
        this.createdAt = Instant.now();
    }

    public UUID getId() {
        return this.id;
    }
}
