classDiagram
    class User {
        +UUID id
        +String username
        +String email
        +String phone
        +Boolean active
    }
    
    class Product {
        +UUID id
        +String name
        +Float price
        +Integer stock
    }