package com.basiccode.generator.generator.django;

import com.basiccode.generator.generator.IMigrationGenerator;
import com.basiccode.generator.model.EnhancedClass;
import java.util.List;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

/**
 * Générateur de migrations Django
 */
public class DjangoMigrationGenerator implements IMigrationGenerator {
    
    @Override
    public String generateMigration(List<EnhancedClass> enhancedClasses, String packageName) {
        if (enhancedClasses == null || enhancedClasses.isEmpty()) {
            return "# No models to migrate\n";
        }
        
        StringBuilder migration = new StringBuilder();
        String timestamp = LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyyMMdd_HHmmss"));
        
        // Migration header
        migration.append("# Generated by Django UML Generator on ").append(timestamp).append("\n\n");
        migration.append("from django.db import migrations, models\n");
        migration.append("import uuid\n\n\n");
        
        // Migration class
        migration.append("class Migration(migrations.Migration):\n\n");
        migration.append("    initial = True\n\n");
        migration.append("    dependencies = [\n");
        migration.append("    ]\n\n");
        
        // Operations
        migration.append("    operations = [\n");
        
        for (EnhancedClass enhancedClass : enhancedClasses) {
            if (enhancedClass.getOriginalClass() != null) {
                generateCreateModelOperation(migration, enhancedClass);
            }
        }
        
        migration.append("    ]\n");
        
        return migration.toString();
    }
    
    private void generateCreateModelOperation(StringBuilder migration, EnhancedClass enhancedClass) {
        String className = enhancedClass.getOriginalClass().getName();
        
        migration.append("        migrations.CreateModel(\n");
        migration.append("            name='").append(className).append("',\n");
        migration.append("            fields=[\n");
        
        // ID field
        migration.append("                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),\n");
        
        // Model fields
        if (enhancedClass.getOriginalClass().getAttributes() != null) {
            enhancedClass.getOriginalClass().getAttributes().forEach(attr -> {
                if (!"id".equals(attr.getName())) {
                    String fieldType = mapToDjangoMigrationField(attr.getType());
                    migration.append("                ('").append(attr.getName().toLowerCase()).append("', ").append(fieldType).append("),\n");
                }
            });
        }
        
        // Audit fields
        migration.append("                ('created_at', models.DateTimeField(auto_now_add=True)),\n");
        migration.append("                ('updated_at', models.DateTimeField(auto_now=True)),\n");
        
        migration.append("            ],\n");
        migration.append("            options={\n");
        migration.append("                'db_table': '").append(className.toLowerCase()).append("',\n");
        migration.append("                'ordering': ['-created_at'],\n");
        migration.append("            },\n");
        migration.append("        ),\n");
    }
    
    private String mapToDjangoMigrationField(String umlType) {
        if (umlType == null) {
            return "models.CharField(max_length=255)";
        }
        
        switch (umlType.toLowerCase()) {
            case "string":
            case "str":
                return "models.CharField(max_length=255)";
            case "integer":
            case "int":
                return "models.IntegerField()";
            case "float":
            case "double":
                return "models.FloatField()";
            case "boolean":
            case "bool":
                return "models.BooleanField(default=False)";
            case "date":
                return "models.DateField()";
            case "datetime":
                return "models.DateTimeField()";
            case "text":
                return "models.TextField()";
            case "email":
                return "models.EmailField()";
            case "url":
                return "models.URLField()";
            default:
                return "models.CharField(max_length=255)";
        }
    }
    
    @Override
    public String getFileExtension() {
        return ".py";
    }
}